---
- name: install node environment
  include: node.yml

- name: install user
  include: user.yml

- name: install hubot
  include: hubot.yml

- name: install hubot packages
  include: hubot_packages.yml

# TODO: should be optional w/ along other process managers like supervisor..
- name: install runit service scripts
  include: runit.yml