---
# runtime
- name: define hubot environment path for runit
  file: >
    path={{ hubot_dir }}/env
    owner={{ hubot_user }}
    group={{ hubot_group }}
    state=directory
    mode=0755

- name: output all environment variables
  copy: >
    dest={{ hubot_dir }}/env/{{ item.key }}
    content={{ item.value }}
    mode=0400
    owner={{ hubot_user }}
    group={{ hubot_group }}
  with_items: hubot_runtime_environment_variables

# 50_hubot.sh..?
- name: install hubot service
  template: src=sv-hubot-run.j2 dest=/etc/service/hubot/run mode=0744

- name: install hubot logging service
  template: src=sv-hubot-log-run.j2 dest=/etc/service/hubot/log/run mode=0744
